
included: # paths to include during linting. `--path` is ignored if present.
  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Flagship
  - FlagShip.podspec
  - Script
  - FlagShip.xcworkspace
  - iOS Example

  line_length: 140