name: Swift
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  Build_SDK:
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'Flagship', destination: 'platform=iOS Simulator,name=iPhone 14', label: 'iOS'}
          - { scheme: 'Flagship-tvOS', destination: 'platform=tvOS Simulator,name=Apple TV', label: 'tvOS' }
          - { scheme: 'Flagship-macOS', destination: 'platform=macOS', label: 'macOS'}
          - { scheme: 'Flagship-watchOS', destination: 'platform=watchOS Simulator,name=Apple Watch SE (40mm) (2nd generation)', label: 'watchOS'}


    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Building SDK for ${{ matrix.run-config['label'] }}
      run: xcodebuild clean build -project Flagship/Flagship.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}'  -destination '${{ matrix.run-config['destination'] }}'
  Testing:
     needs: Build_SDK
     runs-on: macos-latest
     steps:
     - name: Checkout Project
       uses: actions/checkout@v2
     - name: Test SDK Flagship
       run: xcodebuild clean test -project Flagship/Flagship.xcodeproj -scheme "Flagship" -destination "name=iPhone 14"
     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v3
       with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        verbose: true