name: Swift

on: [push, pull_request]
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean test -project Flagship/Flagship.xcodeproj -scheme "Flagship" -destination "name=iPhone 12"
    - name: Upload coverage to codecov
      uses : codecov/codecov-action@v2
