name: Swift
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'Flagship', destination: 'platform=iOS,name=iPhone 14', label: 'SDK Flagship for iOS' }

    steps:
    - name: '${{matrix.run-config['label']}}'
    - uses: actions/checkout@v2
      run: xcodebuild clean test -project Flagship/Flagship.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}'  -destination '${{ matrix.run-config['destination'] }}'


