name: Swift
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'Flagship', destination: 'platform=iOS,name=iPhone', label:"SDK Flagship for iOS" }

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean test -project Flagship/Flagship.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}'  -destination '${{ matrix.run-config['destination'] }}'
   # - name: Update Code Coverage
   #  run: |
   #   bash <(curl -s https://codecov.io/bash)

